defaults: &settings
  version: '2.0.0'
  android_store_url: https://play.google.com/store/apps/details?id=com.zazoapp.client
  iphone_store_url: http://itunes.com/apps/zazo
  domain_name: zazoapp.com
  site_name: zazoapp
  app_name: Zazo
  admin_email: admin@zazoapp.com
  support_email: support@zazoapp.com
  app_schema: "zazo://"
  use_s3: false

development:
  <<: *settings

test:
  <<: *settings

staging:
  <<: *settings

production:
  <<: *settings

