defaults: &settings
  site_url: http://localhost:3000
  android_store_link: market://details?id=com.noplanbees.threebyme
  iphone_store_link: https://itunes.apple.com/us/app/threebyme/id585542753?mt=8
  domain_name: threebyme.com
  site_name: threebyme
  admin_email: admin@threebyme.com
  support_email: support@threebyme.com
  save_last_activity_granularity_in_seconds: 10
  twilio_sender_number: "+14157280387"
  twilio_receiver_number: "+14156020256"
  app_schema: "threebyme://"
  app_photo_directory_name: "threebyme"
  encode_notification_id: false
  min_time_between_notifications_in_minutes: 30
  max_notifications_for_inactive_users: 4
  send_notifications: false
  app_version: 2.0
  madatory_version_upgrade_threshold: 2.0
  android_version_code: 24
  admin_ids:
  - 2
  - 3
  no_notify_ids:
  - 104
  pushwoosh_app_id: 18DB6-47543
  pushwoosh_auth_token: upvWG5eOMVjICGyte65G46Nkxa/ko7E3TOHaaxLlBs2B3egZbBpyNCPe4p6MKIIwjUfgcuuRqjdyhKOFaqpS
  pushwoosh_android_project_id: 926360415491
  s3_bucket: videos.threebyme.com

development: 
  <<: *settings
  send_notifications: false
  use_s3: false

test:
  <<: *settings

staging:
  <<: *settings
  site_url: http://staging.threebyme.com
  s3_bucket: staging.threebyme.com

production:
  <<: *settings
  use_s3: false
  site_url: http://www.threebyme.com
  send_notifications: true

