email:
  from: admin@livingpic.com
  to: sani, ff
  subject_prefix: THREE BY ME
  subject_line_length: 50
  addresses:
    sani: sani@livingpic.com
    ff: ff@livingpic.com
sms:
  from: ThreeByMe <admin@threebyme.com>
  subject_prefix: TBM
  to: ff, sani
  addresses:
    sani: 6502453537@att
    ff: 4156020256@verizon
