email:
  from: elfishawy.sani@gmail.com
  to: sani, andrey
  subject_prefix: ZAZO
  subject_line_length: 50
  addresses:
    sani: elfishawy.sani@gmail.com
    andrey: aboyko@codeminders.com
sms:
  from: elfishawy.sani@gmail.com
  subject_prefix: ZAZO
  to: sani
  addresses:
    sani: 6502453537@att
